### ISSUE TITLE
Module Error: No module named pycocks

### ISSUE THREAD

**Issue by redshark314** [cgshep/pycocks#2]
Hello, I am getting this error in Ubuntu when I use this module. 

ModuleNotFoundError: No module named 'pycocks'

This is my result after installing from pip 
Requirement already satisfied: gmpy2>=2.0.0 in /home/gnakul/.local/lib/python3.7/site-packages (from pycocks) (2.1.5)

I am using python 3 to run the program

**Comment by cgshep** [comment]
Hi, I can't reproduce your error in a virtualenv or any other way. 

Have you seen the following SO thread?
https://stackoverflow.com/questions/45345377/python-module-not-found-even-though-requirement-already-satisfied-in-pip
